language: java
sudo: required

services:
  - docker # required, but travis uses older version of docker :(

script:
  - docker --version
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD 
  - mvn clean verify deploy

   
