language: java
sudo: required

services:
  - docker # required, but travis uses older version of docker :(

cache:
  directories:
  - "$HOME/.cache"

script:
  - docker --version
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD 
  - mvn clean verify 
  
after_success:
  - docker --version
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD 
  - echo $HOME
  - mkdir -p $HOME/releases
  - mkdir -p $HOME/snapshots
  - mvn -DreleaseRepoUrl=$HOME/releases -DsnapshotRepoUrl=$HOME/snapshots deploy   
